CREATE TABLE GUESTBOOK (
    IDX NUMBER PRIMARY KEY, --일련번호
    NAME VARCHAR2(30), --작성자
    SUBJECT VARCHAR2(100), --제목
    CONTENT VARCHAR2(100), --내용
    EMAIL VARCHAR2(100), --이메일
    PWD VARCHAR2(30), --글 작성시 암호
    REGDATE DATE DEFAULT SYSDATE --작성일
    );

CREATE SEQUENCE GUESTBOOK_SEQ NOCACHE;

INSERT INTO GUESTBOOK
    (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍일동', '제목1', '내용1','hong1@test.com','1111', SYSDATE);

INSERT INTO GUESTBOOK
    (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍이동', '제목2', '내용2','hong2@test.com','2222', SYSDATE - 2);

INSERT INTO GUESTBOOK
    (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES (GUESTBOOK_SEQ.NEXTVAL, '홍삼동', '제목3', '내용3','hong3@test.com','3333', SYSDATE - 3);

SELECT *
FROM GUESTBOOK
WHERE IDX='1';

SELECT * 
	    FROM GUESTBOOK
	  ORDER BY IDX;
COMMIT;

delete from guestbook;

BEGIN
    for i in 1 .. 1000 loop
    INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
    VALUES (GUESTBOOK_SEQ.NEXTVAL, CONCAT('홍삼동',TO_CHAR(i)), CONCAT('제목',TO_CHAR(i)), CONCAT('내용',TO_CHAR(i)),CONCAT('hong@test.com',TO_CHAR(i)),TO_CHAR(i+1), SYSDATE-i);
    end loop;
end;